name: explore_mundo
description: "Dos apaixonados para os apaixonados por viagens"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png

  web: false

dependencies:
  flutter:
    sdk: flutter
  intl: 0.19.0
  google_fonts: 6.2.1
  modal_bottom_sheet: 3.0.0
  flutter_native_splash: 2.4.1
  flutter_svg: 2.0.10
  flutter_launcher_icons: 0.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
